### PR TITLE
Add tests. Implement fixes made in the private app. Add CI

### LINKED ISSUE #13: Implement UI tests
UI tests mostly can be copied from the private repos app

### LINKED ISSUE #15: Implement CI actions to test the code
Implement CI actions:
1. Run JUnit tests after every pushed commit
2. Run UI tests on firebase test lab once a day

### PR DESCRIPTION
**Pull request by giorgi-gusakov**
https://github.com/troido/bless-howto/issues/13

### CODE REVIEW

File: app/src/androidTest/java/com/troido/bless/app/base/EnabledBluetoothTestCase.kt [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+            return;
+        }
+
+        val bluetoothStateChanger =
+            BluetoothStateChanger(true, InstrumentationRegistry.getInstrumentation().targetContext)
+        bluetoothStateChanger.process()
+
+        testClass = this.javaClass
+    }
+}
```
Comment (SerhatSurguvec) [inline app/src/androidTest/java/com/troido/bless/app/base/EnabledBluetoothTestCase.kt]: There are no new lines at the end of the file including gradle files. Could you please change it?

**Review by SerhatSurguvec — CHANGES_REQUESTED** [review]

File: app/src/androidTest/java/com/troido/bless/app/base/EnabledBluetoothTestCase.kt (hunk 1 above)
Comment (giorgi-gusakov) [reply app/src/androidTest/java/com/troido/bless/app/base/EnabledBluetoothTestCase.kt]: I'll add ktlint plugin which formats the code automatically

**Review by SerhatSurguvec — APPROVED** [review]
Looks good to me.
